export const NARRATION_PACKED_FILES = [
  "dist/engine/narration_request.js",
  "dist/engine/narration_evidence.js",
  "dist/scripts/narration_check.js",
  "dist/docs/standards/video-generation.md",
  "dist/docs/standards/frameworks/hyperframes.md",
  "dist/docs/standards/frameworks/remotion.md",
] as const;

export const REQUIRED_PACKED_FILES = [
  "dist/bin/md2vid.js",
  "dist/scripts/build.js",
  "dist/scripts/plan.js",
  "dist/scripts/plan_project.js",
  "dist/scripts/check_release_name.js",
  "dist/scripts/cli_args.js",
  "dist/scripts/hyperframes_cli.js",
  "dist/scripts/managed_file_transaction.js",
  "dist/scripts/install_skill.js",
  "dist/scripts/upgrade.js",
  "dist/scripts/package_root.js",
  "scripts/dependency_versions.ts",
  "scripts/package_root.ts",
  "dist/scripts/platform_support.js",
  "dist/scripts/project_layout.js",
  "dist/scripts/scaffold_project.js",
  "dist/scripts/skill_references.js",
  "dist/engine/visual_beats.js",
  "dist/engine/visual_evidence.js",
  "dist/engine/visual_sync.js",
  "dist/frameworks/assets.js",
  "dist/frameworks/hyperframes/visual_timing.js",
  "dist/frameworks/remotion/visual_bindings.js",
  "dist/frameworks/hyperframes/templates/caption-skin.html",
  "dist/frameworks/remotion/templates/render.ts",
  "dist/frameworks/remotion/templates/remotion.config.ts",
  "dist/frameworks/remotion/templates/tsconfig.json",
  "dist/frameworks/remotion/templates/src/index.ts",
  "dist/frameworks/remotion/templates/src/Root.tsx",
  "dist/frameworks/remotion/templates/src/Video.tsx",
  "dist/frameworks/remotion/templates/src/VisualBeats.tsx",
  "dist/docs/standards/frameworks/remotion.md",
  "docs/standards/frameworks/remotion.md",
  "postinstall.mjs",
  "skill/md2vid/SKILL.md",
  "skill/md2vid/references/standards/video-generation.md",
  "skill/md2vid/references/standards/git.md",
  "skill/md2vid/references/standards/design/frame.md",
  "skill/md2vid/references/standards/design/knowledge-expression.md",
  "skill/md2vid/references/standards/design/frame-content.md",
  "skill/md2vid/references/standards/frameworks/hyperframes.md",
  "skill/md2vid/references/standards/frameworks/remotion.md",
  "README.md",
  "LICENSE",
  ...NARRATION_PACKED_FILES,
] as const;

export const FORBIDDEN_PACKED_PREFIXES = [
  "outputs/",
  "test/",
  "node_modules/",
  "docs/superpowers/",
  "examples/",
  "frameworks/hyperframes/templates/",
] as const;

const removedGsapVendorFile = ["vendor", ["gsap", "min", "js"].join(".")].join("/");

export const FORBIDDEN_PACKED_FILES = [
  `frameworks/hyperframes/templates/${removedGsapVendorFile}`,
  `dist/frameworks/hyperframes/templates/${removedGsapVendorFile}`,
] as const;
